[package]
name = "promscale_rs"
version = "0.1.3"
authors = ["Joshua Lockerman <josh@timescale.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
default = []
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
pgx = {git="https://github.com/JLockerman/pgx.git", branch="reduce-type-id-lookup"}
pgx-macros = {git="https://github.com/JLockerman/pgx.git", branch="reduce-type-id-lookup"}

[dev-dependencies]
pgx-tests = {git="https://github.com/JLockerman/pgx.git", branch="reduce-type-id-lookup"}