[package]
name = "promscale"
version = "0.4.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
panic = "unwind" # Ensures that we don't abort a Postgres process
opt-level = 3
lto = "fat"
debug = true
codegen-units = 1

[profile.dev]
panic = "unwind"
lto = "thin"

[features]
default = []
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg14 = ["pgx/pg14", "pgx-tests/pg14"]
pg_test = []

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
pgx = "0.2.1"
pgx-macros = "0.2.1"

[dev-dependencies]
pgx-tests = "0.2.1"
