name: docker
on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker:
        - docker-image-ts2-14
        - docker-image-ts2-13
        - docker-image-ts2-12
        - docker-image-ts1
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build docker image
        run: make ${{ matrix.docker }}
        env:
          DOCKER_BUILDKIT: 1
